INSERT INTO produto (imagem, nome, descricao, valor, link_compra, link_encomenda) VALUES
('img/31.jpg', 'Bolo de Chocolate', 'Delicioso bolo de chocolate com cobertura cremosa.', 29.90, 'finalizarcompra.html', 'https://api.whatsapp.com/send?phone=seu_numero'),
('img/32.jpg', 'Cupcake de Baunilha', 'Macio e saboroso cupcake de baunilha com glacê.', 9.50, 'finalizarcompra.html', 'https://api.whatsapp.com/send?phone=seu_numero'),
('img/33.jpg', 'Torta de Morango', 'Torta fresca com morangos e creme.', 25.00, 'finalizarcompra.html', 'https://api.whatsapp.com/send?phone=seu_numero'),
('img/34.jpg', 'Macaron de Framboesa', 'Delicados macarons com sabor de framboesa.', 3.00, 'finalizarcompra.html', 'https://api.whatsapp.com/send?phone=seu_numero'),
('img/20.jpg', 'Bolo Red Velvet', 'Clássico bolo Red Velvet com cobertura de cream cheese.', 35.00, 'finalizarcompra.html', 'https://api.whatsapp.com/send?phone=seu_numero'),
('img/26.jpg', 'Cheesecake de Morango', 'Cheesecake cremoso com cobertura de morango.', 30.00, 'finalizarcompra.html', 'https://api.whatsapp.com/send?phone=seu_numero'),
('img/15.jpg', 'Brigadeiro Gourmet', 'Brigadeiros gourmet com diversos sabores.', 1.50, 'finalizarcompra.html', 'https://api.whatsapp.com/send?phone=seu_numero'),
('img/19.jpg', 'Brownie de Chocolate', 'Brownies macios e intensamente chocolatudos.', 12.00, 'finalizarcompra.html', 'https://api.whatsapp.com/send?phone=seu_numero'),
('img/43.jpg', 'Torta de Limão', 'Torta de limão com merengue.', 22.00, 'finalizarcompra.html', 'https://api.whatsapp.com/send?phone=seu_numero'),
('img/50.jpg', 'Pão de Mel', 'Pão de mel recheado com doce de leite.', 7.00, 'finalizarcompra.html', 'https://api.whatsapp.com/send?phone=seu_numero'),
('img/39.jpg', 'Donuts', 'Donuts variados com cobertura colorida.', 5.00, 'finalizarcompra.html', 'https://api.whatsapp.com/send?phone=seu_numero'),
('img/10.jpg', 'Muffin de Blueberry', 'Muffins macios com blueberries.', 8.00, 'finalizarcompra.html', 'https://api.whatsapp.com/send?phone=seu_numero'),
('img/11.jpg', 'Palha Italiana', 'Palha italiana tradicional.', 4.00, 'finalizarcompra.html', 'https://api.whatsapp.com/send?phone=seu_numero'),
('img/18.jpg', 'Cookies de Chocolate', 'Cookies crocantes com pedaços de chocolate.', 6.00, 'finalizarcompra.html', 'https://api.whatsapp.com/send?phone=seu_numero'),
('img/26.jpg', 'Cheesecake de Framboesa', 'Cheesecake com framboesas frescas.', 32.00, 'finalizarcompra.html', 'https://api.whatsapp.com/send?phone=seu_numero');
